# Setup
title:            ''
url: "https://jeffrey-t-liu.github.io"
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap


